participants:
  - el_type: geth
    cl_type: lighthouse
  - el_type: evm
    el_image: "ghcr.io/hanzoai/reth:kurtosis-ci"
    cl_type: teku
additional_services:
  - assertoor
assertoor_params:
  run_block_proposal_check: true
  run_transaction_test: true
  run_blob_transaction_test: true
  run_opcodes_transaction_test: true
